parameters:
#    ikantam_files.example.class: Ikantam\FilesBundle\Example
    upload_handler.error_messages:
        1:  'The uploaded file exceeds the upload_max_filesize directive in php.ini'
        2: 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form'
        3: 'The uploaded file was only partially uploaded'
        4: 'No file was uploaded'
        6: 'Missing a temporary folder'
        7: 'Failed to write file to disk'
        8: 'A PHP extension stopped the file upload'
        'post_max_size': 'The uploaded file exceeds the post_max_size directive in php.ini'
        'max_file_size': 'File is too big'
        'min_file_size': 'File is too small'
        'accept_file_types': 'Filetype not allowed'
        'max_number_of_files': 'Maximum number of files exceeded'
        'max_width': 'Image exceeds maximum width'
        'min_width': 'Image requires a minimum width'
        'max_height': 'Image exceeds maximum height'
        'min_height': 'Image requires a minimum height'

    upload_handler.options:
        user_dirs: false
        mkdir_mode: 0755
        param_name: 'files'
        delete_type: 'DELETE'
        access_control_allow_origin: '*'
        access_control_allow_credentials: false
        access_control_allow_methods: ['OPTIONS', 'HEAD', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE']
        access_control_allow_headers: ['Content-Type', 'Content-Range', 'Content-Disposition']
        download_via_php: false,
        readfile_chunk_size: 10 * 1024 * 1024
        inline_file_types: '/\.(gif|jpe?g|png)$/i'
        accept_file_types: '/.+$/i'
        max_file_size: null
        min_file_size: 1
        max_number_of_files: null
        max_width: null
        max_height: null
        min_width: 1
        min_height: 1
        discard_aborted_uploads: true
        orient_image: true
        image_versions: []

    upload_handler.initialize: false

    upload_handler.upload_directory: '/upload/'
    upload_handler.temp_directory: 'temp/'

    upload_handler.class: Ikantam\FilesBundle\Service\Uploader\UploadHandler
    uploaded_files_manager.class: Ikantam\FilesBundle\Service\FilesManager\Manager

services:
    i_uploader:
        class: %upload_handler.class%
        arguments: [@service_container]

    i_uploaded_files_manager:
        class: %uploaded_files_manager.class%
        arguments: [@service_container]